# Snowveil Framework Contract Definition
# ================================
# Defines output schema for both Snowveil flake and generated user flakes
# Used for flake output type checking and discovery by Nix tools
#
# Standardized output discovery:
# - Meta flake (snowveil framework itself) declares its own outputs
# - User flakes generated by mkFlake include flakeOutputsSchema in their outputs
# - Tools can query flakeOutputsSchema to discover legal flake outputs
#
# References:
# - https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-flake.html
# - Nix RFC 87: Trusted users in flakes (schema discussion)

{ lib }:

{
  # Known outputs for meta flake (snowveil framework itself)
  metaFlakeOutputs = {
    # Programming interface
    lib = "attribute set - Snowveil library, types, and utilities";
    
    # User-facing
    templates = "attribute set - flake templates (default)";
    
    # Quality assurance
    checks = "per-system derivations - framework self-tests and validations";
    devShells = "per-system attribute - development environment (default)";
    formatter = "per-system derivation - code formatting tool";
    
    # Documentation
    options = "per-system text file - NixOS options documentation (JSON)";
    flakeOutputsSchema = "attribute set - this schema documentation";
  };

  # Standard outputs for user flakes (generated by mkFlake)
  # These are auto-generated by the framework, but can be selectively enabled/disabled per project
  # See mkFlake's outputs.disabled parameter
  userFlakeOutputs = {
    # Host and user configuration (core)
    nixosConfigurations = "attribute set - NixOS host configurations (key = hostname)";
    homeConfigurations = "attribute set - Home Manager user configurations (key = user@host or user)";
    
    # Packages and applications
    packages = "per-system derivations - buildable packages";
    apps = "per-system app specifications - application wrappers";
    
    # Modules and capability extensions
    nixosModules = "attribute set - reusable NixOS modules (key = grouped.path)";
    homeModules = "attribute set - reusable Home Manager modules (key = grouped.path)";
    
    # Dependency management
    overlays = "attribute set - nixpkgs overlays (key = name)";
    
    # Development and testing
    devShells = "per-system attribute - development environments (key = name)";
    checks = "per-system derivations - tests and verification checks";
    
    # Output artifacts
    images = "attribute set - system images (NixOS ISO, VM images, etc.)";
    deploy = "attribute set - deploy configuration (for automated deployment)";
    formatter = "per-system derivation - code formatting tool";
    
    # Library and extensions
    lib = "attribute set - project-specific library functions and utilities";
  };

  # Complete reference for standardization
  documentationNote = ''
    Snowveil framework marks all known outputs by explicitly declaring flakeOutputsSchema.
    This reduces "unknown flake output" warnings from Nix tools (like nix flake show).
    
    The schema is both human-readable and tool-parsable to enable automation.
  '';

  # 所有已知的 output 类型（不含系统维度）
  allKnownOutputTypes = [
    # 元 flake
    "lib"
    "templates"
    "checks"
    "devShells"
    "formatter"
    "options"
    "flakeOutputsSchema"
    # 用户 flake
    "nixosConfigurations"
    "homeConfigurations"
    "packages"
    "apps"
    "nixosModules"
    "homeModules"
    "overlays"
    "images"
    "deploy"
  ];
}
